name: tearmusic
description: Music Player Frontend

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.18.0-271.4.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.5
  uni_links: ^0.5.1
  clipboard: ^0.1.3
  provider: ^6.0.3
  ionicons: ^0.2.1
  lottie: ^1.4.1
  http: ^0.13.5
  animations: ^2.0.3
  figma_squircle: ^0.5.3
  like_button: ^2.0.4
  loading_animation_widget: ^1.2.0+2
  image: ^3.2.0
  intl: ^0.17.0
  just_audio: ^0.9.28
  audio_session: ^0.1.10
  audio_service: ^0.18.7
  firebase_core: ^1.20.1
  cbor: ^5.1.0
  uuid: ^3.0.6
  pubnub:
    git:
      url: https://github.com/55nknown/pubnub
      ref: master
      path: pubnub

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.otf
          weight: 900
        - asset: fonts/Montserrat/Montserrat-BlackItalic.otf
          weight: 900
          style: italic
        - asset: fonts/Montserrat/Montserrat-ExtraBold.otf
          weight: 800
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: fonts/Montserrat/Montserrat-Bold.otf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/Montserrat/Montserrat-SemiBold.otf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/Montserrat/Montserrat-Medium.otf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/Montserrat/Montserrat-Regular.otf
          weight: 400
        - asset: fonts/Montserrat/Montserrat-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/Montserrat/Montserrat-Light.otf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/Montserrat/Montserrat-ExtraLight.otf
          weight: 200
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/Montserrat/Montserrat-Thin.otf
          weight: 100
        - asset: fonts/Montserrat/Montserrat-ThinItalic.otf
          weight: 100
          style: italic
